import os, paramiko
HOST=os.environ.get("SSH_HOST","111.229.190.132"); PORT=int(os.environ.get("SSH_PORT","22"))
USER=os.environ.get("SSH_USER","root"); PW=os.environ.get("SSH_PW","")
SD="/www/wwwroot/rry.klai.top/server"
def run(c,cmd,t=30):
    i,o,e=c.exec_command(cmd,timeout=t); out=o.read().decode("utf-8","replace"); err=e.read().decode("utf-8","replace"); rc=o.channel.recv_exit_status(); return out,err,rc
c=paramiko.SSHClient(); c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect(HOST,port=PORT,username=USER,password=PW,timeout=15,look_for_keys=False,allow_agent=False)
print("=== node 进程 ===")
out,_,_=run(c,"pgrep -af 'node' || echo NONE")
print(out.strip())
print("=== 端口监听 ===")
out,_,_=run(c,"ss -tlnp 2>/dev/null | grep -E ':3000|:3999|:8080|:80 ' ; echo '---'; netstat -tlnp 2>/dev/null | grep -E ':3000|:3999'")
print(out.strip())
print("=== startup.log 末尾 ===")
out,_,_=run(c,f"tail -60 {SD}/logs/startup.log 2>/dev/null || echo 'NO LOG'")
print(out.strip())
print("=== package.json scripts ===")
out,_,_=run(c,f"grep -A15 '\"scripts\"' {SD}/package.json 2>/dev/null || echo 'NO scripts'")
print(out.strip())
print("=== app.js 启动端口来源 ===")
out,_,_=run(c,f"grep -n 'PORT\\|listen\\|process.env.PORT' {SD}/app.js | head -10")
print(out.strip())
print("=== .env 是否存在 ===")
out,_,_=run(c,f"ls -la {SD}/.env {SD}/.env.enc 2>/dev/null; test -f {SD}/.env && echo 'PLAINTEXT .env EXISTS' || echo 'PLAINTEXT .env GONE'")
print(out.strip())
print("=== 手动尝试前台启动(5秒)看报错 ===")
out,err,_=run(c,f"cd {SD} && timeout 5 su -s /bin/bash www -c 'NODE_ENV=development node app.js' 2>&1 | head -40", t=20)
print("STDOUT:", out.strip())
print("STDERR:", err.strip())
c.close()
